// AUTO-GENERATED by gen_config.py -- DO NOT EDIT
// Source: engine_config.schema.json

#pragma once

#include "engine_config.hpp"
#include <string>
#include <unordered_map>

namespace engine {

// Property key strings for options.properties I/O
struct ConfigPropertyKeys {
    static constexpr const char* inactivityFpsLimit = "inactivityFpsLimit";
    static constexpr const char* maxFps = "maxFps";
    static constexpr const char* outputScale2x = "outputScale2x";
    static constexpr const char* vsync = "vsync";
    static constexpr const char* dlssQuality = "dlssQuality";
    static constexpr const char* upscalerMode = "upscalerMode";
    static constexpr const char* upscalerQuality = "upscalerQuality";
    static constexpr const char* upscalerResOverride = "upscalerResOverride";
    static constexpr const char* areaLightsEnabled = "areaLightsEnabled";
    static constexpr const char* eonDiffuse = "eonDiffuse";
    static constexpr const char* greedyMeshingEnabled = "greedyMeshingEnabled";
    static constexpr const char* multiScatterGGX = "multiScatterGGX";
    static constexpr const char* noiseLOD = "noiseLOD";
    static constexpr const char* ommBakerLevel = "ommBakerLevel";
    static constexpr const char* ommEnabled = "ommEnabled";
    static constexpr const char* pomEnabled = "pomEnabled";
    static constexpr const char* pomFadeDistance = "pomFadeDistance";
    static constexpr const char* pomHeightScale = "pomHeightScale";
    static constexpr const char* pomRefinement = "pomRefinement";
    static constexpr const char* pomSteps = "pomSteps";
    static constexpr const char* rayBounces = "rayBounces";
    static constexpr const char* restirBounceEnabled = "restirBounceEnabled";
    static constexpr const char* restirCandidates = "restirCandidates";
    static constexpr const char* restirEnabled = "restirEnabled";
    static constexpr const char* restirSimplifiedBRDF = "restirSimplifiedBRDF";
    static constexpr const char* restirSpatialRadius = "restirSpatialRadius";
    static constexpr const char* restirSpatialTaps = "restirSpatialTaps";
    static constexpr const char* restirTemporalMClamp = "restirTemporalMClamp";
    static constexpr const char* restirWClamp = "restirWClamp";
    static constexpr const char* serEnabled = "serEnabled";
    static constexpr const char* serHintsEnabled = "serHintsEnabled";
    static constexpr const char* shadowSoftness = "shadowSoftness";
    static constexpr const char* sharcEnabled = "sharcEnabled";
    static constexpr const char* sharcRoughnessThreshold = "sharcRoughnessThreshold";
    static constexpr const char* sharcSceneScale = "sharcSceneScale";
    static constexpr const char* simplifiedIndirect = "simplifiedIndirect";
    static constexpr const char* brightAdaptSpeed = "brightAdaptSpeed";
    static constexpr const char* centerWeightStrength = "centerWeightStrength";
    static constexpr const char* darkAdaptSpeed = "darkAdaptSpeed";
    static constexpr const char* exposureCompensation = "exposureCompensation";
    static constexpr const char* highlightWeight = "highlightWeight";
    static constexpr const char* manualExposure = "manualExposure";
    static constexpr const char* manualExposureEnabled = "manualExposureEnabled";
    static constexpr const char* sceneChangeThreshold = "sceneChangeThreshold";
    static constexpr const char* Lwhite = "Lwhite";
    static constexpr const char* casSharpness = "casSharpness";
    static constexpr const char* colorExpansion = "colorExpansion";
    static constexpr const char* psychoEnabled = "psychoEnabled";
    static constexpr const char* psychoPeakSDR = "psychoPeakSDR";
    static constexpr const char* saturation = "saturation";
    static constexpr const char* saturationAdaptive = "saturationAdaptive";
    static constexpr const char* sharpenerMode = "sharpenerMode";
    static constexpr const char* tonemappingMode = "tonemappingMode";
    static constexpr const char* bloomEnabled = "bloomEnabled";
    static constexpr const char* bloomIntensity = "bloomIntensity";
    static constexpr const char* bloomThreshold = "bloomThreshold";
    static constexpr const char* frameGenEnabled = "frameGenEnabled";
    static constexpr const char* frameGenMultiplier = "frameGenMultiplier";
    static constexpr const char* maxFpsLimit = "maxFpsLimit";
    static constexpr const char* reflexBoost = "reflexBoost";
    static constexpr const char* reflexEnabled = "reflexEnabled";
    static constexpr const char* cloudAltitude = "cloudAltitude";
    static constexpr const char* cloudAmbientStrength = "cloudAmbientStrength";
    static constexpr const char* cloudAtmosphereFadeDist = "cloudAtmosphereFadeDist";
    static constexpr const char* cloudCellFrequency = "cloudCellFrequency";
    static constexpr const char* cloudCoverage = "cloudCoverage";
    static constexpr const char* cloudDebugMode = "cloudDebugMode";
    static constexpr const char* cloudDensity = "cloudDensity";
    static constexpr const char* cloudDetailStrength = "cloudDetailStrength";
    static constexpr const char* cloudNoiseScale = "cloudNoiseScale";
    static constexpr const char* cloudQuality = "cloudQuality";
    static constexpr const char* cloudScatterOctaves = "cloudScatterOctaves";
    static constexpr const char* cloudSpeed = "cloudSpeed";
    static constexpr const char* cloudTemporalBlend = "cloudTemporalBlend";
    static constexpr const char* cloudThickness = "cloudThickness";
    static constexpr const char* cloudType = "cloudType";
    static constexpr const char* cloudWindAngle = "cloudWindAngle";
    static constexpr const char* offlineAccumEnabled = "offlineAccumEnabled";
    static constexpr const char* offlineAperture = "offlineAperture";
    static constexpr const char* offlineBounces = "offlineBounces";
    static constexpr const char* offlineDenoised = "offlineDenoised";
    static constexpr const char* offlineDlssEpochLength = "offlineDlssEpochLength";
    static constexpr const char* offlineFocalDistance = "offlineFocalDistance";
    static constexpr const char* displacementQuality = "displacementQuality";
    static constexpr const char* tessFarDist = "tessFarDist";
    static constexpr const char* tessMaxLevel = "tessMaxLevel";
    static constexpr const char* tessMidDist = "tessMidDist";
    static constexpr const char* tessNearDist = "tessNearDist";
    static constexpr const char* chunkBuildingBatchSize = "chunkBuildingBatchSize";
    static constexpr const char* chunkBuildingTotalBatches = "chunkBuildingTotalBatches";
    static constexpr const char* chunkCullDistance = "chunkCullDistance";
    static constexpr const char* chunkLodDistance = "chunkLodDistance";
    static constexpr const char* gpuDiagnostics = "gpuDiagnostics";
    static constexpr const char* validationLayers = "validationLayers";
    static constexpr const char* diagLevel = "diagLevel";
    static constexpr const char* diagFlags = "diagFlags";
};

enum class RestartScope { None, Pipeline, Renderer, Game };

inline RestartScope getRestartScope(ConfigKey key) {
    switch (key) {
        case ConfigKey::INACTIVITY_FPS_LIMIT: return RestartScope::None;
        case ConfigKey::MAX_FPS: return RestartScope::None;
        case ConfigKey::OUTPUT_SCALE2X: return RestartScope::Pipeline;
        case ConfigKey::VSYNC: return RestartScope::Pipeline;
        case ConfigKey::DLSS_QUALITY: return RestartScope::Pipeline;
        case ConfigKey::UPSCALER_MODE: return RestartScope::Pipeline;
        case ConfigKey::UPSCALER_QUALITY: return RestartScope::Pipeline;
        case ConfigKey::UPSCALER_RES_OVERRIDE: return RestartScope::Pipeline;
        case ConfigKey::AREA_LIGHTS_ENABLED: return RestartScope::None;
        case ConfigKey::EON_DIFFUSE: return RestartScope::None;
        case ConfigKey::GREEDY_MESHING_ENABLED: return RestartScope::Renderer;
        case ConfigKey::MULTI_SCATTER_GGX: return RestartScope::None;
        case ConfigKey::NOISE_LOD: return RestartScope::None;
        case ConfigKey::OMM_BAKER_LEVEL: return RestartScope::Renderer;
        case ConfigKey::OMM_ENABLED: return RestartScope::Renderer;
        case ConfigKey::POM_ENABLED: return RestartScope::None;
        case ConfigKey::POM_FADE_DISTANCE: return RestartScope::None;
        case ConfigKey::POM_HEIGHT_SCALE: return RestartScope::None;
        case ConfigKey::POM_REFINEMENT: return RestartScope::None;
        case ConfigKey::POM_STEPS: return RestartScope::None;
        case ConfigKey::RAY_BOUNCES: return RestartScope::None;
        case ConfigKey::RESTIR_BOUNCE_ENABLED: return RestartScope::None;
        case ConfigKey::RESTIR_CANDIDATES: return RestartScope::None;
        case ConfigKey::RESTIR_ENABLED: return RestartScope::None;
        case ConfigKey::RESTIR_SIMPLIFIED_BRDF: return RestartScope::None;
        case ConfigKey::RESTIR_SPATIAL_RADIUS: return RestartScope::None;
        case ConfigKey::RESTIR_SPATIAL_TAPS: return RestartScope::None;
        case ConfigKey::RESTIR_TEMPORAL_M_CLAMP: return RestartScope::None;
        case ConfigKey::RESTIR_W_CLAMP: return RestartScope::None;
        case ConfigKey::SER_ENABLED: return RestartScope::None;
        case ConfigKey::SER_HINTS_ENABLED: return RestartScope::None;
        case ConfigKey::SHADOW_SOFTNESS: return RestartScope::None;
        case ConfigKey::SHARC_ENABLED: return RestartScope::None;
        case ConfigKey::SHARC_ROUGHNESS_THRESHOLD: return RestartScope::None;
        case ConfigKey::SHARC_SCENE_SCALE: return RestartScope::None;
        case ConfigKey::SIMPLIFIED_INDIRECT: return RestartScope::None;
        case ConfigKey::BRIGHT_ADAPT_SPEED: return RestartScope::None;
        case ConfigKey::CENTER_WEIGHT_STRENGTH: return RestartScope::None;
        case ConfigKey::DARK_ADAPT_SPEED: return RestartScope::None;
        case ConfigKey::EXPOSURE_COMPENSATION: return RestartScope::None;
        case ConfigKey::HIGHLIGHT_WEIGHT: return RestartScope::None;
        case ConfigKey::MANUAL_EXPOSURE: return RestartScope::None;
        case ConfigKey::MANUAL_EXPOSURE_ENABLED: return RestartScope::None;
        case ConfigKey::SCENE_CHANGE_THRESHOLD: return RestartScope::None;
        case ConfigKey::LWHITE: return RestartScope::None;
        case ConfigKey::CAS_SHARPNESS: return RestartScope::None;
        case ConfigKey::COLOR_EXPANSION: return RestartScope::None;
        case ConfigKey::PSYCHO_ENABLED: return RestartScope::None;
        case ConfigKey::PSYCHO_PEAK_SDR: return RestartScope::None;
        case ConfigKey::SATURATION: return RestartScope::None;
        case ConfigKey::SATURATION_ADAPTIVE: return RestartScope::None;
        case ConfigKey::SHARPENER_MODE: return RestartScope::None;
        case ConfigKey::TONEMAPPING_MODE: return RestartScope::None;
        case ConfigKey::BLOOM_ENABLED: return RestartScope::None;
        case ConfigKey::BLOOM_INTENSITY: return RestartScope::None;
        case ConfigKey::BLOOM_THRESHOLD: return RestartScope::None;
        case ConfigKey::FRAME_GEN_ENABLED: return RestartScope::Pipeline;
        case ConfigKey::FRAME_GEN_MULTIPLIER: return RestartScope::Pipeline;
        case ConfigKey::MAX_FPS_LIMIT: return RestartScope::None;
        case ConfigKey::REFLEX_BOOST: return RestartScope::None;
        case ConfigKey::REFLEX_ENABLED: return RestartScope::None;
        case ConfigKey::CLOUD_ALTITUDE: return RestartScope::None;
        case ConfigKey::CLOUD_AMBIENT_STRENGTH: return RestartScope::None;
        case ConfigKey::CLOUD_ATMOSPHERE_FADE_DIST: return RestartScope::None;
        case ConfigKey::CLOUD_CELL_FREQUENCY: return RestartScope::None;
        case ConfigKey::CLOUD_COVERAGE: return RestartScope::None;
        case ConfigKey::CLOUD_DEBUG_MODE: return RestartScope::None;
        case ConfigKey::CLOUD_DENSITY: return RestartScope::None;
        case ConfigKey::CLOUD_DETAIL_STRENGTH: return RestartScope::None;
        case ConfigKey::CLOUD_NOISE_SCALE: return RestartScope::None;
        case ConfigKey::CLOUD_QUALITY: return RestartScope::None;
        case ConfigKey::CLOUD_SCATTER_OCTAVES: return RestartScope::None;
        case ConfigKey::CLOUD_SPEED: return RestartScope::None;
        case ConfigKey::CLOUD_TEMPORAL_BLEND: return RestartScope::None;
        case ConfigKey::CLOUD_THICKNESS: return RestartScope::None;
        case ConfigKey::CLOUD_TYPE: return RestartScope::None;
        case ConfigKey::CLOUD_WIND_ANGLE: return RestartScope::None;
        case ConfigKey::OFFLINE_ACCUM_ENABLED: return RestartScope::Pipeline;
        case ConfigKey::OFFLINE_APERTURE: return RestartScope::None;
        case ConfigKey::OFFLINE_BOUNCES: return RestartScope::Pipeline;
        case ConfigKey::OFFLINE_DENOISED: return RestartScope::Pipeline;
        case ConfigKey::OFFLINE_DLSS_EPOCH_LENGTH: return RestartScope::Pipeline;
        case ConfigKey::OFFLINE_FOCAL_DISTANCE: return RestartScope::None;
        case ConfigKey::DISPLACEMENT_QUALITY: return RestartScope::None;
        case ConfigKey::TESS_FAR_DIST: return RestartScope::None;
        case ConfigKey::TESS_MAX_LEVEL: return RestartScope::None;
        case ConfigKey::TESS_MID_DIST: return RestartScope::None;
        case ConfigKey::TESS_NEAR_DIST: return RestartScope::None;
        case ConfigKey::CHUNK_BUILDING_BATCH_SIZE: return RestartScope::None;
        case ConfigKey::CHUNK_BUILDING_TOTAL_BATCHES: return RestartScope::None;
        case ConfigKey::CHUNK_CULL_DISTANCE: return RestartScope::None;
        case ConfigKey::CHUNK_LOD_DISTANCE: return RestartScope::None;
        case ConfigKey::GPU_DIAGNOSTICS: return RestartScope::None;
        case ConfigKey::VALIDATION_LAYERS: return RestartScope::Renderer;
        case ConfigKey::DIAG_LEVEL: return RestartScope::None;
        case ConfigKey::DIAG_FLAGS: return RestartScope::None;
        default: return RestartScope::None;
    }
}

} // namespace engine
