#!/usr/bin/env python3
"""
RadSER Config Codegen — generates C++ structs, Java classes, and JNI bridge
from engine_config.schema.json.

Usage:
    python gen_config.py <schema.json> --cpp-out <dir> --java-out <dir> --bridge-out <dir>
"""

import argparse
import json
import os
import sys
from pathlib import Path
from datetime import datetime

HEADER = "// AUTO-GENERATED by gen_config.py -- DO NOT EDIT\n// Source: engine_config.schema.json\n"
JAVA_HEADER = "// AUTO-GENERATED by gen_config.py -- DO NOT EDIT\n// Source: engine_config.schema.json\n"


def load_schema(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def flatten_options(schema: dict) -> list[dict]:
    """Flatten nested category.option into a flat list with category metadata."""
    options = []
    for cat_name, cat_obj in schema.get("properties", {}).items():
        if cat_obj.get("type") != "object":
            continue
        category = cat_obj.get("x-category", cat_name)
        order = cat_obj.get("x-order", 999)
        for opt_name, opt_obj in cat_obj.get("properties", {}).items():
            opt = dict(opt_obj)
            opt["name"] = opt_name
            opt["category"] = category
            opt["category_key"] = cat_name
            opt["category_order"] = order
            options.append(opt)
    return sorted(options, key=lambda o: (o["category_order"], o["name"]))


# --- Type mapping ---

def cpp_type(opt: dict) -> str:
    explicit = opt.get("x-cpp-type")
    if explicit:
        return explicit
    t = opt["type"]
    if t == "boolean":
        return "bool"
    if t == "integer":
        return "uint32_t"
    if t == "number":
        return "float"
    if t == "string":
        return "std::string"
    return "/* unknown */"


def cpp_default(opt: dict) -> str:
    t = opt["type"]
    d = opt.get("default")
    if d is None:
        return "{}"
    if t == "boolean":
        return "true" if d else "false"
    if t == "integer":
        return str(int(d))
    if t == "number":
        # Ensure float suffix
        s = repr(float(d))
        if "e" in s.lower():
            return s + "f"
        if "." not in s:
            s += ".0"
        return s + "f"
    if t == "string":
        return f'"{d}"'
    return str(d)


def java_type(opt: dict) -> str:
    explicit = opt.get("x-java-type")
    if explicit == "int":
        return "int"
    t = opt["type"]
    if t == "boolean":
        return "boolean"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "string":
        return "String"
    return "Object"


def java_default(opt: dict) -> str:
    jt = java_type(opt)
    d = opt.get("default")
    if d is None:
        if jt == "boolean":
            return "false"
        if jt in ("int", "float"):
            return "0"
        return "null"
    if jt == "boolean":
        return "true" if d else "false"
    if jt == "int":
        # If java stores as tenths/percent, convert
        unit = opt.get("x-java-unit")
        if unit == "tenths":
            return str(int(round(d * 10)))
        if unit == "percent":
            return str(int(round(d * 100)))
        return str(int(d))
    if jt == "float":
        s = repr(float(d))
        if "." not in s and "e" not in s.lower():
            s += ".0"
        return s + "f"
    if jt == "String":
        return f'"{d}"'
    return str(d)


def jni_type(opt: dict) -> str:
    jt = java_type(opt)
    mapping = {"boolean": "jboolean", "int": "jint", "float": "jfloat", "String": "jstring"}
    return mapping.get(jt, "jobject")


def camel_to_upper(name: str) -> str:
    """camelCase to UPPER_SNAKE_CASE, preserving acronyms (GGX, LOD, SDR, etc.)."""
    result = []
    for i, c in enumerate(name):
        if c.isupper() and i > 0:
            prev = name[i - 1]
            nxt = name[i + 1] if i + 1 < len(name) else ""
            # Insert underscore before uppercase if:
            # - previous char is lowercase (e.g., ray|B -> ray_B)
            # - OR previous is uppercase but next is lowercase (e.g., GG|X|e -> no break inside GGX,
            #   but GL|Sl -> GL_Sl). This keeps consecutive uppercase (acronyms) together.
            if prev.islower() or (prev.isupper() and nxt.islower()):
                result.append("_")
        result.append(c.upper())
    return "".join(result)


def upper_first(name: str) -> str:
    return name[0].upper() + name[1:] if name else name


def conversion_java_to_cpp(opt: dict) -> str:
    """Return C++ expression to convert JNI value to the C++ field type."""
    unit = opt.get("x-java-unit")
    if unit == "tenths":
        return "static_cast<float>(value) / 10.0f"
    if unit == "percent":
        return "static_cast<float>(value) / 100.0f"
    ct = cpp_type(opt)
    jt = jni_type(opt)
    if ct == "uint32_t" and jt == "jint":
        return "static_cast<uint32_t>(value)"
    if ct == "float" and jt == "jfloat":
        return "value"
    if ct == "bool" and jt == "jboolean":
        return "static_cast<bool>(value)"
    return "value"


# --- C++ generation ---

def gen_cpp_struct(options: list[dict], out_dir: Path):
    """Generate engine_config.hpp with the EngineConfig struct."""
    lines = [HEADER, "#pragma once\n", "#include <cstdint>", "#include <string>\n"]
    lines.append("namespace engine {\n")
    lines.append("struct EngineConfig {")

    current_cat = None
    for opt in options:
        if opt["category_key"] != current_cat:
            current_cat = opt["category_key"]
            lines.append(f"\n    // --- {current_cat} ---")
        doc = opt.get("x-doc", "")
        ct = cpp_type(opt)
        cd = cpp_default(opt)
        lines.append(f"    {ct} {opt['name']} = {cd};  // {doc}")

    lines.append("\n    // --- side-effect flags (not persisted) ---")
    lines.append("    bool needRecreate = false;")
    lines.append("    bool reflexDirty = false;")
    lines.append("};\n")

    # Validation function
    lines.append("// Apply range clamping to all fields with defined bounds.")
    lines.append("inline void validateConfig(EngineConfig& cfg) {")
    for opt in options:
        mn = opt.get("minimum")
        mx = opt.get("maximum")
        if mn is not None and mx is not None:
            ct = cpp_type(opt)
            if ct in ("uint32_t", "float"):
                mn_s = f"{mn}f" if ct == "float" else str(int(mn))
                mx_s = f"{mx}f" if ct == "float" else str(int(mx))
                lines.append(f"    if (cfg.{opt['name']} < {mn_s}) cfg.{opt['name']} = {mn_s};")
                lines.append(f"    if (cfg.{opt['name']} > {mx_s}) cfg.{opt['name']} = {mx_s};")
    lines.append("}\n")

    # Key enum for typed access
    lines.append("enum class ConfigKey {")
    for opt in options:
        lines.append(f"    {camel_to_upper(opt['name'])},")
    lines.append("    COUNT")
    lines.append("};\n")

    lines.append("} // namespace engine\n")

    out_path = out_dir / "engine_config.hpp"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  C++ struct:  {out_path}")


def gen_cpp_defaults(options: list[dict], out_dir: Path):
    """Generate config_defaults.hpp with properties file read/write."""
    lines = [HEADER, "#pragma once\n"]
    lines.append('#include "engine_config.hpp"')
    lines.append("#include <string>")
    lines.append("#include <unordered_map>\n")
    lines.append("namespace engine {\n")

    # Property key → field mapping for load/save
    lines.append("// Property key strings for options.properties I/O")
    lines.append("struct ConfigPropertyKeys {")
    for opt in options:
        lines.append(f'    static constexpr const char* {opt["name"]} = "{opt["name"]}";')
    lines.append("};\n")

    # Restart scope enum
    lines.append("enum class RestartScope { None, Pipeline, Renderer, Game };\n")

    # Per-option restart scope
    lines.append("inline RestartScope getRestartScope(ConfigKey key) {")
    lines.append("    switch (key) {")
    for opt in options:
        scope = opt.get("x-restart-scope", "none")
        scope_val = {"none": "None", "pipeline": "Pipeline", "renderer": "Renderer", "game": "Game"}.get(scope, "None")
        lines.append(f"        case ConfigKey::{camel_to_upper(opt['name'])}: return RestartScope::{scope_val};")
    lines.append("        default: return RestartScope::None;")
    lines.append("    }")
    lines.append("}\n")

    lines.append("} // namespace engine\n")

    out_path = out_dir / "config_defaults.hpp"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  C++ defaults: {out_path}")


# --- JNI bridge generation ---

def gen_jni_bridge(options: list[dict], out_dir: Path):
    """Generate config_bridge.cpp with JNI setters that write to EngineConfig."""
    lines = [HEADER]
    lines.append('#include <jni.h>')
    lines.append('#include <algorithm>')
    lines.append('#include "engine_config.hpp"\n')
    lines.append("// Forward: provided by engine/app at link time")
    lines.append("namespace engine {")
    lines.append("    EngineConfig& activeConfig();")
    lines.append("    // Called after a config write with side effects beyond flag-setting.")
    lines.append("    // Implemented by engine/app. Default is a no-op weak symbol.")
    lines.append("    void onConfigSideEffect(ConfigKey key);")
    lines.append("}\n")

    jni_prefix = "Java_com_radiance_v2_bridge_ConfigBridge"

    # Classify side effects: "flag" effects set cfg.X = Y, "action" effects need a callback
    for opt in options:
        name = opt["name"]
        jt = jni_type(opt)
        conv = conversion_java_to_cpp(opt)
        side = opt.get("x-cpp-side-effect", "")

        lines.append(f'extern "C" JNIEXPORT void JNICALL {jni_prefix}_nativeSet{upper_first(name)}(')
        lines.append(f"    JNIEnv*, jclass, {jt} value, jboolean write) {{")
        lines.append(f"    auto& cfg = engine::activeConfig();")

        # Apply range clamp on C++ side
        mn = opt.get("minimum")
        mx = opt.get("maximum")
        ct = cpp_type(opt)
        if mn is not None and mx is not None and ct in ("uint32_t", "float"):
            if ct == "float":
                lines.append(f"    float converted = {conv};")
                lines.append(f"    cfg.{name} = std::clamp(converted, {mn}f, {mx}f);")
            else:
                lines.append(f"    auto converted = {conv};")
                lines.append(f"    cfg.{name} = std::clamp(converted, static_cast<uint32_t>({int(mn)}), static_cast<uint32_t>({int(mx)}));")
        else:
            lines.append(f"    cfg.{name} = {conv};")

        has_action = False
        if side:
            for stmt in side.split(";"):
                stmt = stmt.strip()
                if not stmt:
                    continue
                # Flag assignments (cfg.X = Y) are inlined
                if "=" in stmt and not stmt.startswith("reset") and not "(" in stmt:
                    lines.append(f"    if (write) cfg.{stmt};")
                else:
                    # Action side effects go through the callback
                    has_action = True

        if has_action:
            lines.append(f"    if (write) engine::onConfigSideEffect(engine::ConfigKey::{camel_to_upper(name)});")

        lines.append("}\n")

    out_path = out_dir / "config_bridge.cpp"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  JNI bridge:  {out_path}")


# --- Java generation ---

def gen_java_config(options: list[dict], out_dir: Path):
    """Generate GeneratedConfig.java with fields, load, save, and native declarations."""
    pkg = "com.radiance.v2.config"
    lines = [JAVA_HEADER]
    lines.append(f"package {pkg};\n")
    lines.append("import java.util.Properties;\n")
    lines.append("public class GeneratedConfig {\n")

    # Fields
    current_cat = None
    for opt in options:
        if opt["category_key"] != current_cat:
            current_cat = opt["category_key"]
            lines.append(f"    // --- {current_cat} ---")
        jt = java_type(opt)
        jd = java_default(opt)
        doc = opt.get("x-doc", "")
        lines.append(f"    public static {jt} {opt['name']} = {jd};  // {doc}")
    lines.append("")

    # Load from Properties
    lines.append("    public static void load(Properties props) {")
    for opt in options:
        name = opt["name"]
        jt = java_type(opt)
        jd = java_default(opt)
        if jt == "boolean":
            lines.append(f'        {name} = Boolean.parseBoolean(props.getProperty("{name}", String.valueOf({jd})));')
        elif jt == "int":
            lines.append(f'        {name} = Integer.parseInt(props.getProperty("{name}", String.valueOf({jd})));')
        elif jt == "float":
            lines.append(f'        {name} = Float.parseFloat(props.getProperty("{name}", String.valueOf({jd})));')
        else:
            lines.append(f'        {name} = props.getProperty("{name}", {jd});')
    lines.append("    }\n")

    # Save to Properties
    lines.append("    public static void save(Properties props) {")
    for opt in options:
        name = opt["name"]
        lines.append(f'        props.setProperty("{name}", String.valueOf({name}));')
    lines.append("    }\n")

    # Push all to native
    lines.append("    public static void pushAllToNative() {")
    for opt in options:
        name = opt["name"]
        lines.append(f"        nativeSet{upper_first(name)}({name}, false);")
    lines.append("    }\n")

    # Native declarations
    for opt in options:
        name = opt["name"]
        jt = java_type(opt)
        lines.append(f"    public static native void nativeSet{upper_first(name)}({jt} value, boolean write);")
    lines.append("")

    lines.append("}")

    out_path = out_dir / "GeneratedConfig.java"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  Java config: {out_path}")


def gen_java_ui_metadata(options: list[dict], out_dir: Path):
    """Generate ConfigUIMetadata.java with UI control info for settings screens."""
    pkg = "com.radiance.v2.config"
    lines = [JAVA_HEADER]
    lines.append(f"package {pkg};\n")
    lines.append("import java.util.List;")
    lines.append("import java.util.ArrayList;\n")
    lines.append("public class ConfigUIMetadata {\n")

    lines.append("    public enum ControlType { TOGGLE, SLIDER, DROPDOWN }\n")
    lines.append("    public enum RestartScope { NONE, PIPELINE, RENDERER, GAME }\n")

    lines.append("    public record OptionMeta(")
    lines.append("        String key, String category, ControlType control,")
    lines.append("        String doc, RestartScope restartScope,")
    lines.append("        double min, double max, double step,")
    lines.append("        String[] enumLabels, boolean experimental")
    lines.append("    ) {}\n")

    lines.append("    public static final List<OptionMeta> ALL = new ArrayList<>();\n")
    lines.append("    static {")
    for opt in options:
        name = opt["name"]
        cat = opt.get("category", "")
        ctrl = opt.get("x-ui-control", "toggle").upper()
        doc = opt.get("x-doc", "").replace('"', '\\"')
        scope = opt.get("x-restart-scope", "none").upper()
        mn = opt.get("minimum", 0)
        mx = opt.get("maximum", 0)
        step = opt.get("x-step", 0)
        experimental = "true" if opt.get("x-experimental") else "false"

        enum_map = opt.get("x-enum", {})
        if enum_map:
            labels = ", ".join(f'"{v}"' for v in enum_map.values())
            enum_arr = f"new String[]{{{labels}}}"
        else:
            enum_arr = "null"

        lines.append(f'        ALL.add(new OptionMeta("{name}", "{cat}", ControlType.{ctrl},')
        lines.append(f'            "{doc}", RestartScope.{scope},')
        lines.append(f'            {mn}, {mx}, {step}, {enum_arr}, {experimental}));')

    lines.append("    }")
    lines.append("}")

    out_path = out_dir / "ConfigUIMetadata.java"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  Java UI meta: {out_path}")


# --- Main ---

def main():
    parser = argparse.ArgumentParser(description="RadSER Config Codegen")
    parser.add_argument("schema", help="Path to engine_config.schema.json")
    parser.add_argument("--cpp-out", required=True, help="C++ output directory")
    parser.add_argument("--java-out", required=True, help="Java output directory")
    parser.add_argument("--bridge-out", required=True, help="JNI bridge output directory")
    args = parser.parse_args()

    schema = load_schema(args.schema)
    options = flatten_options(schema)
    print(f"Loaded {len(options)} options from {len(schema.get('properties', {}))} categories\n")

    cpp_dir = Path(args.cpp_out)
    java_dir = Path(args.java_out)
    bridge_dir = Path(args.bridge_out)

    gen_cpp_struct(options, cpp_dir)
    gen_cpp_defaults(options, cpp_dir)
    gen_jni_bridge(options, bridge_dir)
    gen_java_config(options, java_dir)
    gen_java_ui_metadata(options, java_dir)

    print(f"\nDone. {len(options)} options generated across 5 files.")


if __name__ == "__main__":
    main()
