#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0, rgba32f) uniform image2D accumBuffer;
layout(binding = 1, rgba32f) uniform readonly image2D noisyInput;

layout(push_constant) uniform PC {
    int frameCount;
} pc;

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(pixel, imageSize(noisyInput)))) return;

    vec4 newSample = imageLoad(noisyInput, pixel);
    float N = float(pc.frameCount + 1);
    vec4 avg;
    if (pc.frameCount == 0) {
        avg = newSample;
    } else {
        vec4 oldAvg = imageLoad(accumBuffer, pixel);
        avg = oldAvg + (newSample - oldAvg) / N;  // Welford running average
    }
    imageStore(accumBuffer, pixel, avg);
}
